### ISSUE TITLE
 How to incrementally add an index？

### ISSUE THREAD

**Issue by AmierCheng** [microsoft/SPTAG#100]
How to incrementally add an index？ 
We are expecting a reply！
Thanks！

**Comment by karzand** [comment]
This is how I do it in python. 
if index is None it creates the index, if it exists it add to it. This has also meta data included. 

def testAddWithMetaData(index, x, s, out, algo, distmethod):
    if index != None:
        i = SPTAG.AnnIndex.Load(index)
        i.SetBuildParam("NumberOfThreads", '16')
        i.SetBuildParam("DistCalcMethod", distmethod)
        result= i.AddWithMetaData(x, s, x.shape[0])
        print(result)
        i.Save(out)
    else:
        i = SPTAG.AnnIndex(algo, 'Float', x.shape[1])
        i.SetBuildParam("NumberOfThreads", '16')
        i.SetBuildParam("DistCalcMethod", distmethod)
        result= i.BuildWithMetaData(x, s, x.shape[0],True)
        print(result)
        i.Save(out)

**Comment by AmierCheng** [comment]
> This is how I do it in python.
> if index is None it creates the index, if it exists it add to it. This has also meta data included.
> 
> def testAddWithMetaData(index, x, s, out, algo, distmethod):
> if index != None:
> i = SPTAG.AnnIndex.Load(index)
> i.SetBuildParam("NumberOfThreads", '16')
> i.SetBuildParam("DistCalcMethod", distmethod)
> result= i.AddWithMetaData(x, s, x.shape[0])
> print(result)
> i.Save(out)
> else:
> i = SPTAG.AnnIndex(algo, 'Float', x.shape[1])
> i.SetBuildParam("NumberOfThreads", '16')
> i.SetBuildParam("DistCalcMethod", distmethod)
> result= i.BuildWithMetaData(x, s, x.shape[0],True)
> print(result)
> i.Save(out)

Thanks, I see. I do it good.
