### ISSUE TITLE
CMake Error at Wrappers/cmake_install.cmake:87 (file):   file INSTALL cannot find   ".../SPTAG/Wrappers/src/SPTAG.py"

### ISSUE THREAD

**Issue by blueapplehe** [microsoft/SPTAG#101]
CMake Error at Wrappers/cmake_install.cmake:87 (file):   file INSTALL cannot find   ".../SPTAG/Wrappers/src/SPTAG.py"

how can I slove it

**Comment by m0baxter** [comment]
Probably need to install swig

**Comment by scarlett2018** [comment]
@blueapplehe - may you try what @m0baxter suggested and update us here? thanks.

**Comment by scarlett2018** [comment]
> @blueapplehe - may you try what @m0baxter suggested and update us here? thanks.

closing the issue as answer had been provided and no feedback for months.

**Comment by mcelhennyi** [comment]
I am having this same issue with commit d1403f24ef39832426fff27c5dc86ed00fb9ab25 (Master today when I pulled it)

Swig version 3.0.12 apt-get installed.

It builds fine but fails on the make install command.
