### ISSUE TITLE
Error copying file "SPTAG/Wrappers/inc/SPTAGClient.py" to "SPTAG/Release/".

### ISSUE THREAD

**Issue by ojmakhura** [microsoft/SPTAG#21]
**Description**I get an error when compiling. The error seems related to copying of files from the Wrappers/inc folder to the Release folder. When I compile I get the following error.

`Error copying file "/home/junior/programming/builds/SPTAG/Wrappers/inc/SPTAGClient.py" to "/home/junior/programming/builds/SPTAG/Release/".
make[2]: *** [Wrappers/CMakeFiles/_SPTAGClient.dir/build.make:246: ../Release/_SPTAGClient.so] Error 1
make[2]: *** Deleting file '../Release/_SPTAGClient.so'
make[1]: *** [CMakeFiles/Makefile2:386: Wrappers/CMakeFiles/_SPTAGClient.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`

**To Reproduce**
1. git clone
2. cd SPTAG
3. mkdir build
4. cd ubild && cmake .. && make

**Desktop (please complete the following information):**
 - OS: Fedora 30
 - Python 2.7

**Comment by dugarsumit** [comment]
Make sure that swig >= 3.0 is installed. It is needed for generating python wrappers, without this *.py files are not generated and hence you get the above errors.

**Comment by ojmakhura** [comment]
Thanks. Worked like a charm.
