### ISSUE TITLE
I have completed the installation and testing, but  how to use it in python? 

### ISSUE THREAD

**Issue by cjyjack** [microsoft/SPTAG#22]
ModuleNotFoundError: No module named 'SPTAG'

**Comment by dugarsumit** [comment]
A quick fix would be to put your .py file in the Release directory and add the following line just before the import of SPTAG.

`sys.path.append('path to Release directory')`

**Comment by cjyjack** [comment]
In my Release directory, i  can't find SPTAG.py. Only libSPTAG.so can be find.

**Comment by cjyjack** [comment]
Thanks for four help.But , i can't find SPTAG.py in my Release directory , only libSPTAG.so can be find.

**Comment by dugarsumit** [comment]
You can also refer this [issue](https://github.com/microsoft/SPTAG/issues/21), it might be helpful for you.

**Comment by cjyjack** [comment]
Thanks for your help.
