### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit__SPTAG)

### ISSUE THREAD

**Issue by shashi-netra** [microsoft/SPTAG#25]
**Describe the bug**
Ubuntu 18.04 installed SPTAG and trying to run the sample code [here](https://github.com/microsoft/SPTAG/blob/master/docs/GettingStart.md). 
Also added this snippet based on a different issue:

```
import sys
sys.path.append('./Release')
import SPTAG
import numpy as np

n = 100
k = 3
r = 3
: 
:
```

**Additional context**
I get this error message:
```Traceback (most recent call last):
  File "test_ann.py", line 3, in <module>
    import SPTAG
  File "./Release/SPTAG.py", line 15, in <module>
    import _SPTAG
ImportError: dynamic module does not define module export function (PyInit__SPTAG)
```

what am I doing wrong?

**Comment by CloudBreadPaPa** [comment]
Hello, @shashi-netra 

I checked below information first.
https://stackoverflow.com/questions/15291500/i-have-2-versions-of-python-installed-but-cmake-is-using-older-version-how-do

When I ran the cmake, it shows referencing python 2.7 version, but I'm using Anaconda python 3.6.

in build directory, check your 'CMakeCache.txt' python version.
in my case, it was pointing 2.7 libs.

I changed below two params.
//Path to a file.
Python2_INCLUDE_DIR:PATH=/usr/include/python3.5m

//Path to a library.
Python2_LIBRARY_RELEASE:FILEPATH=/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu/libpython3.5m.so

if you can't see '/usr/include/python3.5m' dir, run below command to install python-dev
```
sudo apt-get install -y python3-dev
```
your directory path might vary. change your cmake cache file and check the cmake beginning of result.
it should be 
```
...
-- Could NOT find Python2: Found unsuitable major version "3", but required major version is exact version "2"
-- Found Python.
-- Include Path: /home/USERNAME/anaconda3/include/python3.7m
-- Library Path: /home/USERNAME/anaconda3/lib/libpython3.7m.so
...
```

before run cmake command, move previous Release dir and run it.
