### ISSUE TITLE
Bug when debugging SSDServing in visual studio  

### ISSUE THREAD

**Issue by jinwei14** [microsoft/SPTAG#341]
**Describe the bug**
Hi I am trying to set some break point and run through the code SSDServing code. However, I got this bug (see screenshots below). The bug will disappear by simply remove this line. https://github.com/microsoft/SPTAG/blob/55ca655c6613b54db9d2aff3494a6ec2286db09d/AnnService/src/SSDServing/main.cpp#L172

my questions are : 
1. Why my build runs without any issue but debug fail?
2.This line has been defined twice, does anyone have clue why? 

**To Reproduce**
1. set up SSDServing as start up project
2. Debug 
3. Start debugging.

**Expected behavior**
goes into main function

**Screenshots**
![image](https://user-images.githubusercontent.com/26280459/198506809-aa73f4a5-ce7e-4a3b-8530-d04fb88db2f2.png)

**Additional context**
no_

**Comment by jinwei14** [comment]
the logger is initialized as a global parameter which may cause this issue.

**Comment by PhilipBAdams** [comment]
Should be resolved by https://github.com/microsoft/SPTAG/pull/358.
