### ISSUE TITLE
The SPTAG module caused Python to stop working.

### ISSUE THREAD

**Issue by deepxuexi** [microsoft/SPTAG#37]
The SPTAG module caused Python to stop working.
Fault Description: I am using SPTAG source code compiled with python3.6 64-bit VS2017, test.exe test passed.
Under Windows 7, Python 3.6 can import the SPTAG module. I have successfully indexed 1 million data, but when my data volume exceeds 1 million, an error occurs. The specific tips are:
PYTHON has stopped working,
Problem Event Name: BEX64
Application name: python.exe
Application version: 3.6.150.1013
Fault module name: ucrtbase.DLL
Exception code: C0000417
I went to the Internet to find a solution. Some people said that it is the reason for the VC runtime library, but I still installed the VC2015 and VC2017 runtime libraries.

Also, I noticed that when the program fails, the word "Start to build BKTree" does not appear after ""Setting DistCalcMethod", but it appears directly:
"Save Data To xxxxx\vectors.bin"
Save Data(0,1) Finish!
Save BKT to xxxxx\tree.bin
An error window will pop up here, prompting "Python has stopped working"

**Comment by deepxuexi** [comment]
I thought about it for one night and suspected that this error was caused by the fopen function in the source code. The reason is:
    My data is 1 million 512-dimensional vectors, 1000000*512*4bytes(float32)≈2G, and the fopen function does not support opening files larger than 2G, so when the index I want to build is greater than 2G, the program will report an error.
    In order to verify my thoughts: I reduced the data dimension to 256 dimensions, or 1 million vectors, this time no mistakes, then I increased to 1.5 million vectors, still no error - because the index file vector.bin to be saved Not more than 2G.
How to solve this problem?

**Comment by MaggieQi** [comment]
It is the Wrapper bug. I have fixed it now, you can pull the newest master and have a try : )
