### ISSUE TITLE
Improve the BalancedDataPartition program

### ISSUE THREAD

**Issue by suppersam1** [microsoft/SPTAG#408]
My machine only has 64G of memory, and I cannot build a 128G vector data set.The BalancedDataPartition program may solve my problem, as I can divide the 128G data into multiple parts and build them on multiple machines.However, BalancedDataPartition also reads the entire data set into memory and performs clustering, and my 64G memory still cannot meet this condition.I hope BalancedDataPartition program can support multiple batches of reads to complete clustering with small memory.  Thank you very much!

**Comment by Danbaiwq** [comment]
How do you finally solve reading entire dataset into memory, we meet the same question.

**Comment by suppersam1** [comment]
> How do you finally solve reading entire dataset into memory, we meet the same question.

The BalancedDataPartition should actually implement the idea of distributed kmeans. I modified the code to load data in batches for kmeans on a single machine
