### ISSUE TITLE
How does SPTAG handle sparse vectors?

### ISSUE THREAD

**Issue by shashi-netra** [microsoft/SPTAG#52]
**Is your feature request related to a problem? Please describe.**
I want to use SPTAG to do kNN queries on vectors from a TF-IDF vectorizer, usually sparse vectors. Can I use sparse vectors in SPTAG or rather do you have an idea of how it might perform with sparsity?

**Comment by MaggieQi** [comment]
Currently, we do not support sparse vectors. One quick solution is to try to compress the sparse vectors to the low-dimensional compacted vectors using some deep learning algorithms. Another solution is that you can try to modify (or add new) Dataset and DistanceUtils to do read, write and distance computation for the sparse vectors.
