### ISSUE TITLE
DLL load failed when import SPTAG

### ISSUE THREAD

**Issue by Arctanxy** [microsoft/SPTAG#55]
I have built the project successfully，but when I import SPTAG, I met this error:
`
>>> import sys
>>> sys.path.append(r"D:\library\github_repositories\SPTAG-2\build\Release")
>>> import SPTAG
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\library\github_repositories\SPTAG-2\build\Release\SPTAG.py", line 15, in <module>
    import _SPTAG
ImportError: DLL load failed: 找不到指定的模块。`

The files in folder build/Release are:

_SPTAG.exp
_SPTAG.lib
_SPTAG.pyd
_SPTAGClient.exp
_SPTAGClient.lib
_SPTAGClient.pyd
aggregator.exe
client.exe
indexbuilder.exe
search.exe
server.exe
SPTAG.py
SPTAGClient.py
SPTAGLib.dll
SPTAGLib.lib
test.exe

my environments are :

vs2015
python3.6
windows7

Could anyone tell me the solution for this error?

**Comment by SC4RECOIN** [comment]
I was getting the same issue when using python3.6 but switching to python2.7 resolved it

**Comment by MaggieQi** [comment]
@Arctanxy If you directly use the SPTAG.sln to build the project, it will download python2.7 library and use python2.7 library to generate the dll. If you want to use python3.6, you can use cmake and make sure that python include and library are correct.

**Comment by zhjc** [comment]
I find SPTAG.py and SPTAGClient.py neither in repo, nor generated automation during build in my vs2017, anyone else happened this ?

**Comment by Arctanxy** [comment]
Thank you @MaggieQi
