### ISSUE TITLE
Windows = "Could not find TBB!"

### ISSUE THREAD

**Issue by robertdetroit** [microsoft/SPTAG#66]
I installed the latest version of TBB through anaconda (https://anaconda.org/intel/tbb), but for some reason, every time I try to build SPTAG, it keeps stopping with "CMake Error at CMakeLists.txt:109 (message): Could not find TBB!"

Does anyone know a work-around for this? In the case that this is due to a faulty TBB installation, does anyone have some insight on how to properly install it on their windows machine (Visual Studio 2019)? All the available TBB installation documentation that I found are very outdated.

**Comment by RioMichael** [comment]
I got the same issue when I tried to build SPTAG. Fixed the issue by changing line 96 and 97 of the CmakeList.txt to:
find_path(TBB_INCLUDE_DIRS tbb/tbb.h HINTS ${TBB_DIR} "your path to tbb folder" PATH_SUFFIXES include)
find_library(TBB_LIBRARIES tbb${CMAKE_STATIC_LIBRARY_SUFFIX} HINTS ${TBB_DIR} "your path to tbb folder" PATH_SUFFIXES ${TBB_LIBRARY_SUFFIX})
Depends on different system, you may need to change in another condition.

My system:
OS: Windows 10
Python: python 2.7

**Comment by deepxuexi** [comment]
> stallation documentation that I found are very outdated.
1.download the file : tbb2019_20190410oss_win.zip and extract it , you will find the dir "tbb2019_20190410oss" ,rename the dir name to "TBB".
2. move the dir "TBB" to path "C:\Program Files\Intel\" (if path not exist , create it).
3. OK!

my OS is win10, VS2017.

**Comment by robertdetroit** [comment]
@RioMichael @deepxuexi Thank you both - worked like a charm
