### ISSUE TITLE
Unable to use the C# wrapper

### ISSUE THREAD

**Issue by lambday** [microsoft/SPTAG#68]
I was trying to use the C# wrapper and faced some issues. Here are the things I tried:
- Built the CSHARPSPTAG.dll compiling the CSHARPSPTAG project in VS17. But I was unable to add reference to this dll directly to a C# project. It said
```
A reference to 'path\to\CSHARPSPTAG.dll' could not be added. Please make sure that the file is accessible, and that it is a valid assembly or COM component.
```
- Following [this](https://stackoverflow.com/questions/8616193/how-to-compile-swig-generated-c-sharp-files-into-a-net-dll) and [this](https://stackoverflow.com/questions/31807289/how-can-i-add-a-swig-generated-c-dll-reference-to-a-c-sharp-project), I created a new C# DLL project with the swig generated `*.cs` files to make a .NET dll that I can add reference to. I then added `SPTAGLib.dll` and `CSHARPSPTAG.dll` in the `\bin\Release\` dir of my project. This time, I was able to get it compiled, but when I ran it, it threw an exception
```
System.TypeInitializationException was unhandled
Message: An unhandled exception of type 'System.TypeInitializationException' occurred in ConsoleTest.exe
Additional information: The type initializer for 'CSHARPSPTAGPINVOKE' threw an exception.
```
- I also tried adding all the `TBB` related dlls into the bin of my C# project but none of it seems to work.

Can any of you share how you managed to make it work?

**Comment by MaggieQi** [comment]
@lambday I created a new C# console application project, and add swig generated *.cs files into it. Try to build the project with Allow unsafe code, Platform target x64, Configuration Release. Then copy the CSHARPSPTAG.dll and tbb*.dll to the bin\Release directory of the project.  You can try this settings. It works on my machine.

**Comment by scarlett2018** [comment]
closing the issue as answer had been provided and no feedback for months.
