### ISSUE TITLE
building sptag gives a boost error

### ISSUE THREAD

**Issue by ckuduvalli** [microsoft/SPTAG#84]
**Describe the bug**
While trying to build sptag using cmake and make on gcc 9.1, I am getting the following error:

error: no matching function for call to 'boost::asio::io_context::strand::strand(boost::asio::execution_context&)'
error: 'class boost::asio::execution_context' has no member named 'get_executor'

~/SPTAG-master/AnnService/src/Socket/Connection.cpp: In constructor 'SPTAG::Socket::Connection::Connection(SPTAG::Socket::ConnectionID, boost::asio::ip::tcp::socket&&, const PacketHandlerMapPtr&, std::weak_ptr<SPTAG::Socket::ConnectionManager>)':
~/SPTAG-master/AnnService/src/Socket/Connection.cpp:29:31: error: no matching function for call to 'boost::asio::io_context::strand::strand(boost::asio::execution_context&)'
   29 |       m_heartbeatStarted(false)
      |                               ^
In file included from /usr/include/boost/asio/io_service_strand.hpp:18,
                 from /home/chaitanya.r/lookalike/SPTAG-master/AnnService/inc/Socket/Connection.h:14,
                 from /home/chaitanya.r/lookalike/SPTAG-master/AnnService/src/Socket/Connection.cpp:4:
/usr/include/boost/asio/io_context_strand.hpp:99:12: note: candidate: 'boost::asio::io_context::strand::strand(boost::asio::io_context&)'
   99 |   explicit strand(boost::asio::io_context& io_context)
      |            ^~~~~~
/usr/include/boost/asio/io_context_strand.hpp:99:44: note:   no known conversion for argument 1 from 'boost::asio::execution_context' to 'boost::asio::io_context&'
   99 |   explicit strand(boost::asio::io_context& io_context)
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
/usr/include/boost/asio/io_context_strand.hpp:89:19: note: candidate: 'constexpr boost::asio::io_context::strand::strand(const boost::asio::io_context::strand&)'
   89 | class io_context::strand
      |                   ^~~~~~
/usr/include/boost/asio/io_context_strand.hpp:89:19: note:   no known conversion for argument 1 from 'boost::asio::execution_context' to 'const boost::asio::io_context::strand&'
In file included from /usr/include/boost/asio/basic_socket.hpp:21,
                 from /usr/include/boost/asio/basic_socket_acceptor.hpp:19,
                 from /usr/include/boost/asio/ip/tcp.hpp:19,
                 from /home/chaitanya.r/lookalike/SPTAG-master/AnnService/inc/Socket/Connection.h:13,
                 from /home/chaitanya.r/lookalike/SPTAG-master/AnnService/src/Socket/Connection.cpp:4:
/usr/include/boost/asio/detail/io_object_impl.hpp: In instantiation of 'boost::asio::detail::io_object_impl<IoObjectService, Executor>::io_object_impl(ExecutionContext&, typename std::enable_if<std::is_convertible<ExecutionContext&, boost::asio::execution_context&>::value>::type*) [with ExecutionContext = boost::asio::execution_context; IoObjectService = boost::asio::detail::deadline_timer_service<boost::asio::time_traits<boost::posix_time::ptime> >; Executor = boost::asio::executor; typename std::enable_if<std::is_convertible<ExecutionContext&, boost::asio::execution_context&>::value>::type = void]':
/usr/include/boost/asio/basic_deadline_timer.hpp:174:20:   required from 'boost::asio::basic_deadline_timer<Time, TimeTraits, Executor>::basic_deadline_timer(ExecutionContext&, typename std::enable_if<std::is_convertible<ExecutionContext&, boost::asio::execution_context&>::value>::type*) [with ExecutionContext = boost::asio::execution_context; Time = boost::posix_time::ptime; TimeTraits = boost::asio::time_traits<boost::posix_time::ptime>; Executor = boost::asio::executor; typename std::enable_if<std::is_convertible<ExecutionContext&, boost::asio::execution_context&>::value>::type = void]'
~/SPTAG-master/AnnService/src/Socket/Connection.cpp:29:31:   required from here
/usr/include/boost/asio/detail/io_object_impl.hpp:87:40: error: 'class boost::asio::execution_context' has no member named 'get_executor'
   87 |       implementation_executor_(context.get_executor(),
      |                                ~~~~~~~~^~~~~~~~~~~~
make[2]: *** [AnnService/CMakeFiles/server.dir/src/Socket/Connection.cpp.o] Error 1
make[1]: *** [AnnService/CMakeFiles/server.dir/all] Error 2
make: *** [all] Error 2

**Desktop (please complete the following information):**
 - Linux Ubuntu

**Comment by mcelhennyi** [comment]
Same here. This is a boost 1.67 vs 1.70 issue
