### ISSUE TITLE
Error while running cmake - undefined reference to 'SPTAG::Helper::DefaultReader::DefaultReader

### ISSUE THREAD

**Issue by javedsha** [microsoft/SPTAG#97]
**Describe the bug**
Error while cmake:

![image](https://user-images.githubusercontent.com/11423719/63698622-20b44980-c817-11e9-9024-6172898f4ef7.png)

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu)
 - Version 18.04

I am getting this same error while running on docker and also on Ubuntu machine 18.04

All the pre-requisite, cmake, boost and swig are installed properly.
Also, attached the CMakeOutput.log

[CMakeOutput.log](https://github.com/microsoft/SPTAG/files/3541605/CMakeOutput.log)

**Comment by javedsha** [comment]
So, basically it looks like an issue with latest master branch. I tried an older commit and it works 😊

**Comment by Gaussly** [comment]
Same problem.So is this a bug?

**Comment by MaggieQi** [comment]
Fixed in the latest version of master branch :)

**Comment by scarlett2018** [comment]
@javedsha @Gaussly - Closing the issue as fixes had committed, please try the latest version from master and reopen if there are still any issues around it. Thanks again for the supports.
